### ISSUE TITLE
How to complile?

### ISSUE THREAD

**Issue by gaurav16chauhan** [Perryo/Compiler-Project#1]
I was trying to compile this code on ubuntu but was having some trouble. It says :
'undefined reference to parse_generate_intermediate_representation'

What am I doing wrong?

**Comment by Perryo** [comment]
Hi gaurav16chauhan,
Thanks for checking out the project. Are you compiling all of these files together using the GCC? 
See this post here:
http://stackoverflow.com/questions/18815399/compiling-multiple-files-in-c
